### ISSUE TITLE
Wrong format name

### ISSUE THREAD

**Issue by vltr** [vltr/middle-schema#2]
Fix from `integer` to `number`.

https://github.com/vltr/middle-schema/blob/8913ea7c5b0952265db7e8b0a78489fa3bc96fad/src/middle_schema/openapi.py#L104

See https://github.com/vltr/sanic-attrs/pull/2/commits/a57c393b9d5852f20b8e2051b72ef13fcabddcf4. Credits and thanks to @abatilo.

**Comment by abatilo** [comment]
Actually, I've since learned that integer and number are supposed to be two different types:
https://swagger.io/docs/specification/data-models/data-types/

**Comment by vltr** [comment]
Ohh ... Well, let me close this then :sweat_smile:
